### ISSUE TITLE
Move constants to dotenv file

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Invoicing#2]
The is a constant variable storing the database name. This can be moved to and loaded from a dotenv file.

https://github.com/sarcoma/Invoicing/blob/master/invoicing/constants/resource_path.py

**Comment by dnegreira** [comment]
Can I take this issue?

**Comment by OrderAndCh4oS** [comment]
> Can I take this issue?

Of course. Let me know if you have any problems getting the project set up.

**Comment by OrderAndCh4oS** [comment]
@dnegreira I've made a significant update to the repo, it'll be worth pulling down the changes, if you're still interested in working on this issue.
