### ISSUE TITLE
Replace LaTeX template examples logo.

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/Invoicing#6]
The invoice logo is still using my personal logo. It would be better if this were replaced with a generic logo.png file.

There will need to be a way to replace the logo too, perhaps reading it from a config file. I'm not sure how to handle dynamic files with pip installs, so I'm open to suggestions.

**Comment by CedArctic** [comment]
I'd like to take a look into it

**Comment by OrderAndCh4oS** [comment]
@CedArctic Thanks so much. Let me know if you have any trouble getting the project set up.
